// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2003, 3, 18),
                            Category = 2,
                            Created = new DateTime(2024, 11, 5, 18, 1, 46, 128, DateTimeKind.Local).AddTicks(6238),
                            Email = "LukasJanus@microsoft.wsei.edu.pl",
                            FirstName = "Lukas",
                            LastName = "Janus",
                            PhoneNumber = "607 758 331"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2003, 7, 18),
                            Category = 2,
                            Created = new DateTime(2024, 11, 5, 18, 1, 46, 128, DateTimeKind.Local).AddTicks(6282),
                            Email = "PawelWrona@microsoft.wsei.edu.pl",
                            FirstName = "Pawel",
                            LastName = "Wrona",
                            PhoneNumber = "111 222 333"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2005, 3, 18),
                            Category = 2,
                            Created = new DateTime(2024, 11, 5, 18, 1, 46, 128, DateTimeKind.Local).AddTicks(6285),
                            Email = "KacperWojas@microsoft.wsei.edu.pl",
                            FirstName = "Kacper",
                            LastName = "Wojas",
                            PhoneNumber = "412 123 123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
